### ISSUE TITLE
No change to PTZ observation output in admin UI for Axis Camera sensors

### ISSUE THREAD

**Issue by ch08532** [opensensorhub/osh-sensors#6]
I was successful in connecting OSH to two AXIS cameras in our lab but do not see any changes to the observable PTZ output (all set to 0.0) when I change either PTZ setting on the camera.  I do see the sampling time change but that's it.  

No errors in the logs.  

Axis cameras are:
AXIS 214 and AXIS Q6115-E

**Comment by ch08532** [comment]
RESOLUTION:  The sensor axis driver in this repo was developed against AXIS VAPIX v2 API.  The AXIS 214 leverages VAPIX v3 API.  The major difference is the url paths.  I've made the changes locally to support VAPIX v3.

**Comment by mikebotts** [comment]
Chris. I'm not sure that the problem was an incompatibility between VAPIX versions but just an old fashion bug that got introduced during some refactoring. I believe that .../axis-cgi/com/ptz.cgi?query=position will retrieve PTZ output in both VAPIX versions.

Either way, you fix takes care of this.
